### PR TITLE
Added supporting LESS, Sass, SCSS

### PR DESCRIPTION
**Pull request by ginlime**
As shown in title.

### CODE REVIEW

**Comment by chinchiheather** [comment]
Thanks for this @ginlime I have noticed a few other people wanting this but haven't got around to it before.

Can you update `package.json` where the `activationEvents` are listed? You will need to add [an activation event](https://code.visualstudio.com/docs/extensionAPI/activation-events#_activationeventsonlanguage) for each of the new file types, there is table [here](https://code.visualstudio.com/docs/languages/identifiers) with the identifiers you'll need to use.

Can you also update the readme to include the new file types too?

Thanks!

**Comment by ginlime** [comment]
@chinchiheather Oh, I see.

I updated files you specified.
Please check them.

**Comment by chinchiheather** [comment]
Looks good @ginlime !

I will merge and release a new version to the marketplace, I think it takes a little while for the newest version to show up

**Comment by ginlime** [comment]
I found newest version in marketplace!
Thanks!

**Pull request merged**
